//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Exclude List.
        /// </summary>
        internal static string AddExcludeList {
            get {
                return ResourceManager.GetString("AddExcludeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Never Follow List.
        /// </summary>
        internal static string AddNeverFollowList {
            get {
                return ResourceManager.GetString("AddNeverFollowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze.
        /// </summary>
        internal static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Createdat.
        /// </summary>
        internal static string Createdat {
            get {
                return ResourceManager.GetString("Createdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Replies.
        /// </summary>
        internal static string DeleteAllReply {
            get {
                return ResourceManager.GetString("DeleteAllReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Retweets.
        /// </summary>
        internal static string DeleteAllRetweets {
            get {
                return ResourceManager.GetString("DeleteAllRetweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string Destroy {
            get {
                return ResourceManager.GetString("Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow All.
        /// </summary>
        internal static string DestroyAll {
            get {
                return ResourceManager.GetString("DestroyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow list.
        /// </summary>
        internal static string DestroyList {
            get {
                return ResourceManager.GetString("DestroyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in export.
        /// </summary>
        internal static string ErrorExport {
            get {
                return ResourceManager.GetString("ErrorExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel allows only 65,536 maximum rows in a sheet..
        /// </summary>
        internal static string ExcelMaxRows {
            get {
                return ResourceManager.GetString("ExcelMaxRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        internal static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow on Twitter.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow All on Twitter.
        /// </summary>
        internal static string FollowAll {
            get {
                return ResourceManager.GetString("FollowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove (unfollow) the selected friends you follow on twitter (can not be undone)?.
        /// </summary>
        internal static string FollowDelete {
            get {
                return ResourceManager.GetString("FollowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove (unfollow) all friends in this list you follow on twitter (can not be undone)?.
        /// </summary>
        internal static string FollowDeleteAll {
            get {
                return ResourceManager.GetString("FollowDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow @twitterapi.
        /// </summary>
        internal static string FollowTwitterApi {
            get {
                return ResourceManager.GetString("FollowTwitterApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has.
        /// </summary>
        internal static string Has {
            get {
                return ResourceManager.GetString("Has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Reply.
        /// </summary>
        internal static string IsReply {
            get {
                return ResourceManager.GetString("IsReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install Microsoft Office (Excel) to use the Export to Excel feature..
        /// </summary>
        internal static string MOfficeInstall {
            get {
                return ResourceManager.GetString("MOfficeInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileImage.
        /// </summary>
        internal static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retweeted.
        /// </summary>
        internal static string Retweeted {
            get {
                return ResourceManager.GetString("Retweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenName.
        /// </summary>
        internal static string ScreenName {
            get {
                return ResourceManager.GetString("ScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet Id.
        /// </summary>
        internal static string TweetId {
            get {
                return ResourceManager.GetString("TweetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate from TweetId Excel (slow).
        /// </summary>
        internal static string TweetIdExcelData {
            get {
                return ResourceManager.GetString("TweetIdExcelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data From Twitter.
        /// </summary>
        internal static string TwitterData {
            get {
                return ResourceManager.GetString("TwitterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Followers.
        /// </summary>
        internal static string TwitterFollowers {
            get {
                return ResourceManager.GetString("TwitterFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter&apos;s user name.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
